### ISSUE TITLE
Empty lines break fullpath

### ISSUE THREAD

**Issue by Startouf** [shanmuganathan-balaraman/jsonyamlkeynavigator#5]
Consider a YAML like

```yaml
topLevelKey:
  nested1: test1
  nested2: test2

  nested3: test3
anotherTopLevelKey:
  nested4: test4
```

When hovering on test values In the status bar it shows

```
topLevelKey.nested1
topLevelKey.nested2
nested3 # broken here
anotherTopLevelKey.nested4
```

tested on macOS Sonoma 14.2
