### ISSUE TITLE
Bug in loating items in an array

### ISSUE THREAD

**Issue by rickyzhang82** [shanmuganathan-balaraman/jsonyamlkeynavigator#6]
When clicked on ` envFrom: []` from the YAML file below, the plugin showed the wrong full path `template.spec.name.envFrom`. 

It skipped the array contains and the index. I would expect `template.spec.containers[0].envFrom` or `template.spec.containers.0.envFrom`.

``` YAML
apiVersion: v1
kind: PodTemplate
metadata:
  labels:
    fooobar.com/admin: namespace
    hello.fooobar.com/class: stateless
  annotations:
    fooobar.com/certificate-file-format: pem
    fooobar.com/kustomize-base: base
  name: $(fooobar_SERVICE_NAME)
template:
  metadata:
    annotations:
      fooobar.com/certificate-file-format: pem
      fooobar.com/kustomize-base: base
    labels:
      workload.fooobar.com/class: stateless
  spec:
    automountServiceAccountToken: false
    imagePullSecrets: []
    initContainers: []
    containers:
    - name: $(fooobar_SERVICE_NAME)
      image: fooobar
      env: []
      envFrom: []
      securityContext:
        allowPrivilegeEscalation: false
        privileged: false
        readOnlyRootFilesystem: true
        capabilities:
          add: []
          drop:
          - ALL
      volumeMounts: []
    restartPolicy: Never
    volumes: []
    tolerations: []
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms: []
        preferredDuringSchedulingIgnoredDuringExecution: []
      podAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: []
        preferredDuringSchedulingIgnoredDuringExecution: []
      podAntiAffinity:
        requiredDuringSchedulingIgnoredDuringExecution: []
        preferredDuringSchedulingIgnoredDuringExecution: []
    securityContext:
      runAsNonRoot: true
      seccompProfile:
        type: RuntimeDefault
```
